---
# tasks file for lighthouse-role
- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: reload-nginx
      become: true
      command: nginx -s reload

- name: Lighthouse | install dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present

- name: Lighthouse | Copy from git
  git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"

- name: Lighthouse | Create lighthouse config
  become: true
  template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: reload-nginx

